# Generated by Django 4.1.4 on 2023-03-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
    ]
