# Generated by Django 4.1.4 on 2023-03-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_follow_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user_main', 'user_follower')},
        ),
    ]
