# Generated by Django 4.1.4 on 2023-03-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_related_likes', to='network.post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
